#!/bin/bash
######################
# QEMU STARTER v 0.1 #
# Creator: Cooleech  #
######################

function SELECT_HDD {
 SelectHDD=`zenity --title "$ScriptName - Odaberi .qvd datoteku (virtualni HDD)" --file-selection --file-filter 'Qemu virtualni disk | *.[Qq][Vv][Dd]'`
 if [ $? != 0 ]; then
  exit
 fi
}

function SELECT_ISO {
 SelectISO=`zenity --title "$ScriptName - Odaberi .iso datoteku" --file-selection --file-filter 'ISO | *.[Ii][Ss][Oo]'`
 if [ $? != 0 ]; then
  exit
 fi
}

function RAM_SIZE {
 RAMsize=`zenity --width 300 --height 350 --list --radiolist --title "$ScriptName" --text "Odaberi količinu RAM-a za VM" \
					--column " ? " --column "RAM u MB" FALSE 256 FALSE 512 FALSE 768 TRUE 1024 FALSE 1536 FALSE 2048`
 if [ $? != 0 ]; then
  exit
 fi
}

function RUN_HDD {
 qemu-system-x86_64 -enable-kvm "$SelectHDD" -smp cores=2 -boot d -net nic -net user -m $RAMsize -localtime
 if [ $? != 0 ]; then
  zenity --error --width 300 --title "$ScriptName" --text "Greška pri pokretanju virtualnog diska!"
  exit
 fi
}

function RUN_ISO {
 qemu-system-x86_64 -enable-kvm -cdrom "$SelectISO" -smp cores=2 -boot d -m $RAMsize
 if [ $? != 0 ]; then
  zenity --error --width 300 --title "$ScriptName" --text "Greška pri pokretanju ISO datoteke!"
  exit
 fi
}

if [ $# -gt 1 ]; then
 zenity --error --title "$ScriptName" --text "Morate odabrati samo jednu datoteku!"
 exit 1
fi

if [ "$1" != "" ]; then
 RAM_SIZE
 case "$1" in
 *qvd)
  SelectHDD="$1"
  RUN_HDD
  exit
 ;;
 *iso)
  SelectISO="$1"
  RUN_ISO
  exit
 ;;
 *)
  zenity --error --title "$ScriptName" --text "Nepodržana datoteka!"
  exit 1
 ;;
 esac
fi

Version="0.1"
ScriptName="${0##*/} $Version"

QemuJob=`zenity --width 300 --height 350 --list --radiolist --title "$ScriptName" --text "Što želiš napraviti s Qemu?" \
					--column " ? " --column "Radnja za Qemu" FALSE "Stvori virtualni HDD" TRUE "Pokreni ISO datoteku" \
						FALSE "Pokreni virtualni HDD" FALSE "Instalacija preko ISO datoteke"`
case "$QemuJob" in
Stv*HDD)
 SaveHDD=`zenity --title "$ScriptName - Spremi datoteku virtualnog diska (.qvd)" --file-selection --save`
 if [ $? != 0 ]; then
  exit
 fi
 HDDsize=`zenity --width 300 --height 350 --list --radiolist --title "$ScriptName" --text "Odaberi veličinu HDD-a za VM" \
					--column " ? " --column "Veličina HDD-a u GB" FALSE 2 FALSE 4 FALSE 6 TRUE 8 FALSE 10 FALSE 15 FALSE 20`
 if [ $? != 0 ]; then
  exit
 fi
 qemu-img create "$SaveHDD.qvd" ${HDDsize}G
 zenity --info --width 300 --title "$ScriptName" --text "Stvoren je virtualni disk:\n\n$SaveHDD.qvd\n\nveličine $HDDsize GB."
;;
Pok*ISO*eku)
 SELECT_ISO
 RAM_SIZE
 RUN_ISO
;;
Pok*vir*HDD)
 SELECT_HDD
 RAM_SIZE
 RUN_HDD
;;
Ins*eke)
 SELECT_ISO
 SELECT_HDD
 RAM_SIZE
 qemu-system-x86_64 -enable-kvm -cdrom "$SelectISO" -hda "$SelectHDD" -smp cores=2 -boot d -net nic -net user -m $RAMsize -localtime
;;
esac

# Examples:
#
# qemu-img create test.qcow 5G
# qemu-system-x86_64 -enable-kvm -cdrom /dev/cdrom -hda test.qcow -boot d -net nic -net user -m 1024 -localtime
# qemu-system-x86_64 test.qcow -boot c -net nic -net user -m 1024 -localtime
#
# qemu-system-x86_64 -enable-kvm -cdrom <isoname>.iso -hda test.qcow -boot d -net nic -net user -m 1024 -localtime
# qemu-system-x86_64 test.qcow -boot c -net nic -net user -m 1024 -localtime
